2014/10/08 14:51:22 [error] [exception.CException] exception 'CException' with message 'Alias "bootstrap.widgets.TbNavbar" is invalid. Make sure it points to an existing PHP file and the file is readable.' in C:\xampp\htdocs\inventory\framework\YiiBase.php:322
Stack trace:
#0 C:\xampp\htdocs\inventory\framework\web\CWidgetFactory.php(146): YiiBase::import('bootstrap.widge...', true)
#1 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'bootstrap.widge...', Array)
#2 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(172): CBaseController->createWidget('bootstrap.widge...', Array)
#3 C:\xampp\htdocs\inventory\protected\views\layouts\main.php(68): CBaseController->widget('bootstrap.widge...', Array)
#4 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#5 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#6 C:\xampp\htdocs\inventory\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#7 C:\xampp\htdocs\inventory\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\inventory\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(206): COutputProcessor->run()
#10 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\inventory\protected\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(126): require('C:\xampp\htdocs...')
#13 C:\xampp\htdocs\inventory\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\xampp\htdocs...', Array, true)
#14 C:\xampp\htdocs\inventory\framework\web\CController.php(784): CBaseController->renderFile('C:\xampp\htdocs...', Array, true)
#15 C:\xampp\htdocs\inventory\protected\controllers\SiteController.php(32): CController->render('index')
#16 C:\xampp\htdocs\inventory\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#17 C:\xampp\htdocs\inventory\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\inventory\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\inventory\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\inventory\framework\web\CWebApplication.php(282): CController->run('')
#21 C:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#22 C:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#23 C:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/inventory/
---
2014/10/08 23:21:00 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\inventory\protected\components\WebUser.php:17)
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\web\CBaseController.php(95): SiteController->renderInternal()
#1 D:\xampp\htdocs\inventory\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#2 D:\xampp\htdocs\inventory\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#3 D:\xampp\htdocs\inventory\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#4 D:\xampp\htdocs\inventory\framework\web\CBaseController.php(206): CContentDecorator->run()
#5 D:\xampp\htdocs\inventory\framework\web\CBaseController.php(300): SiteController->endWidget()
#6 D:\xampp\htdocs\inventory\protected\views\layouts\column1.php(6): SiteController->endContent()
#7 D:\xampp\htdocs\inventory\framework\web\CBaseController.php(126): require()
#8 D:\xampp\htdocs\inventory\framework\web\CBaseController.php(95): SiteController->renderInternal()
#9 D:\xampp\htdocs\inventory\framework\web\CController.php(784): SiteController->renderFile()
#10 D:\xampp\htdocs\inventory\protected\controllers\SiteController.php(32): SiteController->render()
#11 D:\xampp\htdocs\inventory\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#12 D:\xampp\htdocs\inventory\framework\web\CController.php(308): CInlineAction->runWithParams()
#13 D:\xampp\htdocs\inventory\framework\web\CController.php(286): SiteController->runAction()
#14 D:\xampp\htdocs\inventory\framework\web\CController.php(265): SiteController->runActionWithFilters()
#15 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(282): SiteController->run()
#16 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController()
#17 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#18 D:\xampp\htdocs\inventory\index.php(13): CWebApplication->run()
REQUEST_URI=/inventory/index.php?r=site/index
in D:\xampp\htdocs\inventory\protected\components\WebUser.php (17)
in D:\xampp\htdocs\inventory\themes\bootstrap\views\layouts\main.php (24)
in D:\xampp\htdocs\inventory\protected\views\layouts\column1.php (6)
2014/10/08 23:22:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "merk/admin".' in D:\xampp\htdocs\inventory\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('merk/admin')
#1 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventory/index.php?r=merk/admin
HTTP_REFERER=http://localhost:8282/inventory/index.php?r=site/login
---
2014/10/08 23:22:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "supplier/admin".' in D:\xampp\htdocs\inventory\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('supplier/admin')
#1 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventory/index.php?r=supplier/admin
HTTP_REFERER=http://localhost:8282/inventory/index.php?r=merk/admin
---
2014/10/08 23:22:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "supplier/admin".' in D:\xampp\htdocs\inventory\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('supplier/admin')
#1 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventory/index.php?r=supplier/admin
HTTP_REFERER=http://localhost:8282/inventory/index.php?r=supplier/admin
---
2014/10/08 23:24:29 [error] [exception.CException] exception 'CException' with message 'Property "Users.users_id" is not defined.' in D:\xampp\htdocs\inventory\framework\base\CComponent.php:130
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\db\ar\CActiveRecord.php(145): CComponent->__get('users_id')
#1 D:\xampp\htdocs\inventory\protected\components\UserIdentity.php(26): CActiveRecord->__get('users_id')
#2 D:\xampp\htdocs\inventory\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#3 D:\xampp\htdocs\inventory\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 D:\xampp\htdocs\inventory\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 D:\xampp\htdocs\inventory\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#6 D:\xampp\htdocs\inventory\protected\controllers\SiteController.php(94): CModel->validate()
#7 D:\xampp\htdocs\inventory\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 D:\xampp\htdocs\inventory\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 D:\xampp\htdocs\inventory\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 D:\xampp\htdocs\inventory\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(282): CController->run('login')
#12 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 D:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/inventory/index.php?r=site/login
HTTP_REFERER=http://localhost:8282/inventory/index.php?r=site/login
---
2014/10/08 23:24:57 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not authorized to perform this action.' in D:\xampp\htdocs\inventory\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(WebUser), 'You are not aut...')
#1 D:\xampp\htdocs\inventory\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 D:\xampp\htdocs\inventory\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\inventory\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 D:\xampp\htdocs\inventory\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\inventory\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\inventory\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(282): CController->run('admin')
#8 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('salesTransactio...')
#9 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/inventory/index.php?r=salesTransaction/admin
HTTP_REFERER=http://localhost:8282/inventory/index.php?r=site/login
---
2014/10/08 23:25:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "merk/admin".' in D:\xampp\htdocs\inventory\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('merk/admin')
#1 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventory/index.php?r=merk/admin
HTTP_REFERER=http://localhost:8282/inventory/index.php?r=salesTransaction/admin
---
2014/10/08 23:25:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "supplier/admin".' in D:\xampp\htdocs\inventory\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\inventory\framework\web\CWebApplication.php(141): CWebApplication->runController('supplier/admin')
#1 D:\xampp\htdocs\inventory\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\inventory\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/inventory/index.php?r=supplier/admin
HTTP_REFERER=http://localhost:8282/inventory/index.php?r=merk/admin
---
